version: "3"
services:
    db:
        build: ./db
        restart: always
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=train
            - POSTGRES_PASSWORD=choochoo
            - POSTGRES_DB=train
        volumes:
            - /var/lib/postgresql/data

    pgadmin4:
        build: pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: thelochok@gmail.com
            PGADMIN_DEFAULT_PASSWORD: bob
        ports:
            - "2229:80"
        volumes:
            - /var/lib/pgadmin

    dev:
        build: dev
        user: node
        volumes:
            - ./:/home/node/cuberailserver
            - /var/run/docker.sock:/var/run/docker-host.sock
            - ~/.ssh:/home/node/.ssh:ro
        expose:
            - "2230"
        environment: 
            DB: postgres://train:choochoo@db:5432/train
            NODE_ENV: development
        dns:
            - 208.67.222.222
            - 127.0.0.11

    nginx:
        image: nginx:1.19
        ports:
        - "80:80"
        environment:
            SERVER_IMAGE: dev
        volumes:
        - ./nginx/etc_nginx/templates:/etc/nginx/templates:ro
        - ./dist-client:/var/www/clients:ro
        - ./static:/var/www/static:ro

