version: "3"
services:
  db:
    build: ./db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=train
      - POSTGRES_PASSWORD=choochoo
      - POSTGRES_DB=train
    volumes:
      - ./db_data:/var/lib/postgresql/data

  pgadmin4:
    build: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: thelochok@gmail.com
      PGADMIN_DEFAULT_PASSWORD: bob
    ports:
      - "2229:80"
    volumes:
      - /var/lib/pgadmin

  game_server:
    build:
      context: .
      dockerfile: Dockerfile.Server
    environment:
      NODE_ENV: production
      DB: postgres://train:choochoo@db:5432/train
    working_dir: /home/node/game_server
    entrypoint: "npm start"
    expose:
      - "2230"
    dns:
      - 208.67.222.222
      - 127.0.0.11
    restart: always

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    restart: always
    ports:
      - "80:80"
    environment:
      SERVER_IMAGE: game_server
    volumes:
      - ./nginx/etc_nginx/templates:/etc/nginx/templates:ro
      - ./dist-client:/var/www/clients:ro
      - ./static:/var/www/static:ro
    dns:
      - 208.67.222.222
      - 127.0.0.1
