version: "3"
services:
    db:
        build: ./db
        container_name: db
        restart: always
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=train
            - POSTGRES_PASSWORD=choochoo
            - POSTGRES_DB=train
        volumes:
            - /var/lib/postgresql/data

    pgadmin4:
        build: pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: thelochok@gmail.com
            PGADMIN_DEFAULT_PASSWORD: bob
        ports:
            - "8889:80"
        volumes:
            - /var/lib/pgadmin

    dev:
        build: dev
        user: node
        volumes:
            - ./:/home/node/app
            - /var/run/docker.sock:/var/run/docker-host.sock