FROM node

RUN mkdir -p /home/node/.vscode-server/extensions \
        /home/node/.vscode-server-insiders/extensions \
    && chown -R node \
        /home/node/.vscode-server \
        /home/node/.vscode-server-insiders